import 'package:flutter/material.dart';
import 'package:pokedex_secompp/classes/pokemon_type_color.dart';
import 'package:pokedex_secompp/classes/type.dart';

Map<String, PokemonType> pokemonTypes = {
  'normal': PokemonType("Normal",
      PokemonTypeColor(const Color(0xFFA8A77A), const Color(0xFF616040))),
  'fire': PokemonType("Fire",
      PokemonTypeColor(const Color(0xBFFA973B), const Color(0xFFFA8700))),
  'water': PokemonType("Water",
      PokemonTypeColor(const Color(0xBF3B9EFA), const Color(0xFF0055FA))),
  'grass': PokemonType("Grass",
      PokemonTypeColor(const Color(0xAF7CB153), const Color(0xFF77CB80))),
  'electric': PokemonType("Electric",
      PokemonTypeColor(const Color(0xCFEDD261), const Color(0xFFF7D02C))),
  'ice': PokemonType("Ice",
      PokemonTypeColor(const Color(0xFF96D9D6), const Color(0xFF37807C))),
  'fighting': PokemonType("Fighting",
      PokemonTypeColor(const Color(0xFFF56862), const Color(0xFFC22E28))),
  'poison': PokemonType("Poison",
      PokemonTypeColor(const Color(0xFFF283F0), const Color(0xFFA33EA1))),
  'ground': PokemonType("Ground",
      PokemonTypeColor(const Color(0xFFD9BF7E), const Color(0xFFE2BF65))),
  'flying': PokemonType("Flying",
      PokemonTypeColor(const Color(0xFFA98FF3), const Color(0xFF5C42A8))),
  'psychic': PokemonType("Psychic",
      PokemonTypeColor(const Color(0xFFF781A5), const Color(0xFFF95587))),
  'bug': PokemonType("Bug",
      PokemonTypeColor(const Color(0xFFACB85A), const Color(0xFFA6B91A))),
  'rock': PokemonType("Rock",
      PokemonTypeColor(const Color(0xFFBDAf6C), const Color(0xFFB6A136))),
  'ghost': PokemonType("Ghost",
      PokemonTypeColor(const Color(0xFF807391), const Color(0xFF735797))),
  'dark': PokemonType("Dark",
      PokemonTypeColor(const Color(0xFFAB9485), const Color(0xFF705746))),
  'dragon': PokemonType("Dragon",
      PokemonTypeColor(const Color(0xFFBCA4F5), const Color(0xFF6F35FC))),
  'steel': PokemonType("Steel",
      PokemonTypeColor(const Color(0xFFB7B7CE), const Color(0xFF434369))),
  'fairy': PokemonType("Fairy",
      PokemonTypeColor(const Color(0xFFD685AD), const Color(0xFFDE2f85))),
};
